- name: install jdk
  yum : 
    name : java-{{ jdk_version }}-openjdk-devel 
    state: installed 

- name: download yum repository file of jenkins
  get_url: 
    url : "{{ jenkins_repository }}"
    dest: /etc/yum.repos.d/jenkins.repo
    mode: 0644

- name: import rpm key
  rpm_key:
    key  : "{{ jenkins_key }}"
    state: present

- name: install jenkins
  yum : 
    name : jenkins
    state: installed 

- name: set jenkins conf
  template: src=jenkins dest=/etc/sysconfig owner=root group=root mode=0600 

- name: start jenkins
  service:
    name : jenkins
    state: started
    enabled: yes 
