- name: install nginx
  yum : 
    name : nginx
    state: present 

- name: set nginx's ssl conf
  template: src=jenkins.conf dest=/etc/nginx/conf.d/jenkins.conf owner=root group=root mode=0644 

- name: create nginx's ssl server key directory
  file: path=/etc/pki/nginx/private state=directory owner=root group=root mode=0644

#- name: create nginx's ssl server crt directory
#  file: path=/etc/pki/nginx state=directory owner=root group=root mode=0644

- name: create server key
  shell: openssl genrsa 2048 > /etc/pki/nginx/private/server.key

- name: create server csr
  shell: openssl req -new -key /etc/pki/nginx/private/server.key > /etc/pki/nginx/server.csr -subj /C=JP/ST=Tokyo/L=Tokyo/CN={{ inventory_hostname }}

- name: create server crt
  shell: openssl x509 -days 3650 -req -signkey /etc/pki/nginx/private/server.key < /etc/pki/nginx/server.csr > /etc/pki/nginx/server.crt

- name: enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
